version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: desafio1-server
    ports:
      - "8080:8080"
    networks:
      - custom-network
    command: >
      sh -c "nginx -g 'daemon off;'"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: desafio1-client
    depends_on:
      - web-server
    networks:
      - custom-network
    restart: unless-stopped

networks:
  custom-network:
    driver: bridge
    name: desafio1-network


